### PR TITLE
Removed all code and dependencies for behat

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Remove Behat

# Need Review By (Date)
- :shrug: 

# Urgency
- low

# Steps to Test
1. :shrug: 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
Going to wait just a little longer to be sure we got all of them. 

So long old tool.

**Comment by jbickar** [comment]
It had a good run. Technology moves on.

**Comment by sherakama** [comment]
Probably safe to merge this now.

**Comment by pookmish** [comment]
merge

**Pull request merged**
